name: 'WireGuard SSH'
description: 'SSH over WireGuard'
branding:
  icon: 'lock'
  color: 'red'
inputs:
  peer_ip:
    description: 'IP of WireGuard peer'
    required: true
  ssh_public_key:
    description: 'SSH public key'
    required: true
  peer_port:
    description: 'Port of WireGuard peer'
    required: false
  github_ip:
    description: 'Private IP of GitHub peer'
    required: false
  ssh_connection_timeout:
    description: 'Seconds to wait for SSH connection'
    required: false
  session_timeout:
    description: 'Seconds to timeout SSH session'
    required: false
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/wireguard-ssh.sh
      shell: bash
      env:
        PEER_PORT: ${{ inputs.peer_port }}
        PEER_IP: ${{ inputs.peer_ip }}
        GITHUB_IP: ${{ inputs.github_ip }}
        SSH_PUBLIC_KEY: ${{ inputs.ssh_public_key }}
        SSH_CONNECTION_TIMEOUT: ${{ inputs.ssh_connection_timeout }}
        SESSION_TIMEOUT: ${{ inputs.session_timeout }}

